GET http://localhost:5000/contact

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/contact
Content-Type: application/json

{
    "name": "rapi",
    "email": "rapi@gmail.com",
    "message": "akfolaondjf oakenfoan foaknef oaknf oaiej foiakj ofiweja ofiaeh foiaf oljwefo oakwj foiawje fopijawf oi."
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "address": "Cikarang"
}

###
DELETE http://localhost:5000/sampah/8