GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJyYXBpIiwiZW1haWwiOiJyYXBpQGdtYWlsLmNvbSIsImlhdCI6MTczMjM2NjczMSwiZXhwIjoxNzMyMzY2NzQ2fQ.gMqbQ5KiLDGT1g_rVXQf6OviWTKjdU1MLq1YAwq2hPo
###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/articles
Content-Type: application/json

{
    "title": "Recycle",
    "desc": "Apa Itu Penyortiran? Pahami dari dan Cara Mendaurulangnya!",
    "imageUrl": "./src/assets/images/blogs.png",
    "altText": "Recycling symbol made of green leaves",
    "author" : "Photo by TRVST",
    "content" : "Disini kami berdiri"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "rapi@gmail.com",
    "password" : "123456"
}
 
###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

###
PATCH http://localhost:5000/articles/4
Content-Type: application/json

{
    "imageUrl": "./src/assets/images/blogs.png"
}

###
DELETE http://localhost:5000/articles/2